/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import bitcamp.menu.MenuGroup;
import bitcamp.myapp.dao.BoardDao;
import bitcamp.myapp.dao.MemberDao;
import bitcamp.myapp.dao.NoticeDao;
import bitcamp.myapp.dao.mysql.BoardDaoImpl;
import bitcamp.myapp.dao.mysql.MemberDaoImpl;
import bitcamp.myapp.dao.mysql.NoticeDaoImpl;
import bitcamp.myapp.handler.HelpHandler;
import bitcamp.myapp.handler.board.BoardAddHandler;
import bitcamp.myapp.handler.board.BoardDeleteHandler;
import bitcamp.myapp.handler.board.BoardListHandler;
import bitcamp.myapp.handler.board.BoardModifyHandler;
import bitcamp.myapp.handler.board.BoardViewHandler;
import bitcamp.myapp.handler.member.MemberAddHandler;
import bitcamp.myapp.handler.member.MemberDeleteHandler;
import bitcamp.myapp.handler.member.MemberListHandler;
import bitcamp.myapp.handler.member.MemberModifyHandler;
import bitcamp.myapp.handler.member.MemberViewHandler;
import bitcamp.myapp.handler.notice.NoticeAddHandler;
import bitcamp.myapp.handler.notice.NoticeDeleteHandler;
import bitcamp.myapp.handler.notice.NoticeListHandler;
import bitcamp.myapp.handler.notice.NoticeModifyHandler;
import bitcamp.myapp.handler.notice.NoticeViewHandler;
import bitcamp.util.Prompt;
import java.sql.Connection;
import java.sql.DriverManager;

public class App {
    Prompt prompt = new Prompt(System.in);

    BoardDao boardDao;
    BoardDao greetingDao;
    NoticeDao noticeDao;
    MemberDao memberDao;

    MenuGroup mainMenu;

    App() {
        prepareDatabase();
        prepareMenu();
    }

    public static void main(String[] args) {
        System.out.print("( •˓◞•̀ )동아리 커뮤니티입니다.( ⁎ᵕᴗᵕ⁎ )");
        new App().run();
    }

    void prepareDatabase() {
        try {
            // JVM이 JDBC 드라이버 파일(.jar)에 설정된대로 자동으로 처리한다.
//      Driver driver = new com.mysql.cj.jdbc.Driver();
//      DriverManager.registerDriver(driver);

            Connection con = DriverManager.getConnection(

                //"jdbc:mysql://localhost/studydb", "study", "Bitcamp!@#123");
                "jdbc:mysql://db-ld293-kr.vpc-pub-cdb.ntruss.com/studydb", "study", "Bitcamp!@#123");
            boardDao = new BoardDaoImpl(con, 1);
            greetingDao = new BoardDaoImpl(con, 2);
            noticeDao = new NoticeDaoImpl(con);
            memberDao = new MemberDaoImpl(con);

        } catch (Exception e) {
            System.out.println("통신 오류!");
            e.printStackTrace();
        }
    }

    void prepareMenu() {
        mainMenu = MenuGroup.getInstance("메인");

        MenuGroup noticeMenu = mainMenu.addGroup("공지사항");

        noticeMenu.addItem("등록", new NoticeAddHandler(
            noticeDao, prompt));
        noticeMenu.addItem("조회", new NoticeViewHandler(
            noticeDao, prompt));
        noticeMenu.addItem("변경", new NoticeModifyHandler(
            noticeDao, prompt));
        noticeMenu.addItem("삭제", new NoticeDeleteHandler(
            noticeDao, prompt));
        noticeMenu.addItem("목록", new NoticeListHandler(
            noticeDao, prompt));

        MenuGroup boardMenu = mainMenu.addGroup("회원 게시글");

        boardMenu.addItem("등록", new BoardAddHandler(boardDao, prompt));
        boardMenu.addItem("조회", new BoardViewHandler(boardDao, prompt));
        boardMenu.addItem("변경", new BoardModifyHandler(boardDao, prompt));
        boardMenu.addItem("삭제", new BoardDeleteHandler(boardDao, prompt));
        boardMenu.addItem("목록", new BoardListHandler(boardDao, prompt));

        MenuGroup memberMenu = mainMenu.addGroup("회원 관리");

        memberMenu.addItem("등록", new MemberAddHandler(memberDao, prompt));
        memberMenu.addItem("조회", new MemberViewHandler(memberDao, prompt));
        memberMenu.addItem("변경", new MemberModifyHandler(memberDao, prompt));
        memberMenu.addItem("삭제", new MemberDeleteHandler(memberDao, prompt));
        memberMenu.addItem("목록", new MemberListHandler(memberDao, prompt));


        mainMenu.addItem("도움말", new HelpHandler(prompt));
    }

    void run() {
        while (true) {
            try {
                mainMenu.execute(prompt);
                prompt.close();
                break;
            } catch (Exception e) {
                System.out.println("예외 발생!");
            }
        }
    }

}